FROM neosimsim/ghc:8.8.4 as BUILDER
ENV AGDA_VERSION=2.6.1

USER root
RUN adduser -D agda
WORKDIR /src
RUN chown agda /src
USER agda

RUN cabal user-config -a 'install-method: copy' init
RUN cabal v2-update
RUN cabal v2-install Agda-$AGDA_VERSION
RUN cabal v2-install --package-env agda --lib Agda-$AGDA_VERSION ieee754
ENV HOME=/home/agda
ENV PATH=$HOME/bin:$PATH
COPY agda $HOME/bin/agda

# install std-lib
ENV STDLIB_VERSION=1.3

RUN mkdir -p $HOME/lib/agda
WORKDIR $HOME/lib/agda
RUN wget -qO std-lib.zip https://github.com/agda/agda-stdlib/archive/v$STDLIB_VERSION.zip
RUN unzip -q std-lib.zip
RUN rm std-lib.zip
RUN mkdir -p $HOME/.agda
RUN echo $HOME/lib/agda/agda-stdlib-$STDLIB_VERSION/standard-library.agda-lib > $HOME/.agda/libraries-$AGDA_VERSION
RUN echo standard-library > $HOME/.agda/defaults

WORKDIR  /src

FROM BUILDER as TESTER

COPY hello-world.agda .
RUN agda -c --ghc-flag '-static' --ghc-flag '-optl-pthread' --ghc-flag '-optl-static' hello-world.agda
RUN ./hello-world

FROM BUILDER as FINAL
CMD ["/bin/sh"]
